Update IOC for new BO QF (output stage) firmware
lnls-sirius/dev-packages pull request #595
Opened 2020-09-04 20:29 UTC by xresende

2020-09-04 21:24 UTC, fernandohds564 approved these changes

2020-09-08 12:12 UTC, murilobalves approved these changes

2020-09-08 23:01 UTC, gabrielbrunheira requested changes

2020-09-10 17:15 UTC, xresende commented on siriuspy/siriuspy/pwrsupply/bsmp/entities.py
> +        {'eid': 68, 'waccess': False, 'count': 1, 'var_type': _Types.T_UINT32},
fixed. thanks!

2020-09-15 12:18 UTC, gabrielbrunheira approved these changes

2020-09-15 15:35 UTC, merged