Pwrsupply scope
lnls-sirius/dev-packages pull request #670
Opened 2021-03-06 22:29 UTC by xresende

2021-03-07 23:48 UTC, fernandohds564 approved these changes

2021-03-08 11:56 UTC, anacso17 approved these changes

2021-03-08 12:05 UTC, murilobalves approved these changes

2021-03-09 17:21 UTC, gabrielbrunheira requested changes

2021-03-09 17:21 UTC, gabrielbrunheira commented on siriuspy/siriuspy/pwrsupply/csdev.py
> +                             'hilim': 1e4, 'high': 1e4, 'hihi': 1e4},
Change lower limits to 1 Hz (Freq) and 1e-2 s (Duration) and upper limits to 1e5 Hz (Freq) and 4096 s (duration).

2021-03-09 19:51 UTC, xresende reviewed
@gabrielbrunheira , done!

2021-03-09 20:25 UTC, gabrielbrunheira approved these changes

2021-03-10 19:15 UTC, merged