Update PS IOC - other power supplies
lnls-sirius/dev-packages pull request #821
Opened 2022-06-29 15:49 UTC by anacso17

-  Add Alarms-Mon and AlarmsLabels-Cte PVs to other power supply models (FAC_DCDC, FAC_DCDC_EMA, FAC_2S_DCDC, FAC_2P4S_DCDC, FAP, FAP_4P and FAP_2P2S)

This PR correspond to the second stage of firmware update of the next maintenance period, it is the continuation for PR https://github.com/lnls-sirius/dev-packages/pull/820.
Related new BSMP specification can be [accessed here](https://cnpemcamp.sharepoint.com/:x:/s/sei/EdwpNtZ1QItBlvEjc5j_REcBspYu9GkjKm64YNPe8026_Q?e=FDM0L6) .

2022-06-30 12:51 UTC, xresende requested changes

2022-06-30 12:51 UTC, xresende commented on siriuspy/siriuspy/pwrsupply/csdev.py
> +        'PeriodSyncPulseCount-Mon': {
the name `PeriodSyncPulseCount` (ans its corresponding PS variable) is not intuitive for what it meas. Talk @gabrielbrunheira to think a better name.

2022-07-04 15:58 UTC, xresende approved these changes

2022-07-04 16:09 UTC, gabrielbrunheira approved these changes

2022-07-04 17:03 UTC, fernandohds564 approved these changes

2022-07-04 19:14 UTC, murilobalves approved these changes

2022-07-05 15:31 UTC, RafaelLyra8 approved these changes

2022-07-12 14:42 UTC, merged