Changes in BPM and FamBPMs classes
lnls-sirius/dev-packages pull request #924
Opened 2023-03-10 12:11 UTC by murilobalves

Now the methods `get_sampling_frequency` and `get_switching_frequency` are implemented in the `BPM` class. Homonymous methods are still present in the `FamBPMs`, but they just call the methods for each `BPM` device object within the `FamBPMs` and check if their values are the same for all BPMs.

2023-03-10 16:03 UTC, fernandohds564 requested changes

2023-03-10 17:06 UTC, anacso17 approved these changes

2023-03-10 18:04 UTC, murilobalves commented on siriuspy/siriuspy/devices/bpm.py
> +        return self['SwDivClk-RB'] * 2
Ok. I included a docstring with that description.

2023-03-10 19:45 UTC, fernandohds564 approved these changes

2023-03-13 18:08 UTC, xresende approved these changes

2023-03-13 18:19 UTC, merged