Update default values of SOFB and FOFB PVs
lnls-sirius/dev-packages pull request #928
Opened 2023-03-15 15:46 UTC by anacso17

Updating default values of some SOFB and FOFB PVs to values that will be used now with FOFB at 48kHz.

2023-03-15 16:04 UTC, fernandohds564 requested changes

2023-03-15 18:31 UTC, anacso17 commented on siriuspy/siriuspy/sofb/csdev.py
>                  'type': 'enum', 'value': self.EnbldDsbld.Dsbld,
done!

2023-03-15 18:31 UTC, anacso17 commented on siriuspy/siriuspy/sofb/main.py
>              self._download_fofb_kicks = False
done!

2023-03-15 19:04 UTC, murilobalves approved these changes

2023-03-15 19:19 UTC, fernandohds564 approved these changes

2023-03-20 15:42 UTC, RafaelLyra8 approved these changes

2023-03-20 18:53 UTC, xresende approved these changes

2023-03-20 19:15 UTC, merged